# Generated by Django 3.1.2 on 2020-10-30 22:39

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Workplace',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('address', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Zone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('poly', django.contrib.gis.db.models.fields.PolygonField(srid=4326)),
                ('workplace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='zones', to='workplace.workplace')),
            ],
        ),
    ]
