# Generated by Django 3.1.2 on 2020-10-31 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workplace', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='workplace',
            name='contract',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='workplace',
            name='contractor',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='workplace',
            name='customer',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='workplace',
            name='squares',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
